baresip/rem

- src/aubuf/aubuf.c
aubuf: read also last frame if it has not the full size
If the last frame in the aubuf is smaller than the wanted size, then aubuf_read
should return this part and fill up to the rest of the frame with silence.
In most use cases complete frames are pushed. But module/aufile also uses aubuf and may finish with writing a partly frame. If this final frame is not pushed into the auplay, it may lead to an unclean end.
> aubuf: read also last frame if it has not the full size

- Makefile
E.g. for cross compilation it may be necessary to specify the location of
re.mk where make is called.
@sreimers Same solution in baresip/Makefile. What I have found by reading Makefile doc and by small test Makefiles is that the ":=" always overwrites the variable. Setting LIBRE_MK from outside  was not possible. So it seems to be the correct solution?
> Makefile: allow LIBRE_MK to be set outside

- Makefile
- include/rem_audio.h
- include/rem_auframe.h
- src/auframe/auframe.c
- src/auframe/mod.mk
Move `auframe` to rem, so we can add `aubuf` functions like 
```c
int  aubuf_init_auframe(struct aubuf *ab, struct auframe *af);
int  aubuf_write_auframe(struct aubuf *ab, struct auframe *af);
void aubuf_read_auframe(struct aubuf *ab, struct auframe *af);
```
> auframe: move to rem

- Makefile
@sreimers This fixes the build for cross compilation projects.
It is not always the case that re lies beside rem.
For cross compilation e.g. yocto projects at least LIBRE_MK has to be set. From this path LIBRE_PKG_PATH can be retrieved by path substitution.
Similar for baresip: https://github.com/baresip/baresip/pull/1486
> mk: support more locations for libre.pc

- include/rem_auframe.h
Only update necessary fields (since `srate`, `fmt` and `ch` should not change).
For example currently a audio record handler looks like this:
```c
record_handler(...)
{
struct auframe af;
...
auframe_init(&af, st->prm.fmt, sampv, sampc, st->prm.srate, st->prm.ch);
af.timestamp = AUDIO_TIMEBASE*inStartTime->mSampleTime / st->prm.srate;
...
}
```
new api:
```c
record_alloc(...)
{
auframe_init(st->af, fmt, NULL, sampc, srate, ch);
}
record_handler(...)
{
struct ausrc_st *st = userData;
...
auframe_update(st->af, sampv, sampc, timestamp);
...
}
```
> auframe: add auframe_update

- docs/aubuf/.gitignore
- docs/aubuf/README.md
- docs/aubuf/accounts
- docs/aubuf/ajb.plot
- docs/aubuf/config
- docs/aubuf/generate_plots.sh
- include/rem_aubuf.h
- include/rem_auframe.h
- src/aubuf/ajb.c
- src/aubuf/ajb.h
- src/aubuf/aubuf.c
- src/aubuf/mod.mk
- src/auframe/auframe.c
This a rework on the adaptive jitter buffer algorithm in `re/src/jbuf`.
Discussion: https://github.com/baresip/re/discussions/184
Relates to https://github.com/baresip/baresip/pull/1784.
For G.711 the `jbuf` can be dropped (`jitter_buffer_type  off`). What means that each RTP packet is immediately passed to the decoder. The `aubuf` handles re-ordered audio frames.
For state-full codecs like G.722, opus the `jbuf` has a new option (`jitter_buffer_type  minimize`). In this case still `jbuf` has to handle re-ordered packets. But the `minimize` mode ensures that the `jbuf` latency is adjusted on the frequency of "packet to late" occurrences.
The `jitter_buffer_type  adaptive` becomes obsolete. --> Simplifies `re/src/jbuf/jbuf.c` and `baresip/src/audio.c`.
- aubuf: compute input jitter and …
> aubuf adaptive jitter buffer

- docs/aubuf/.gitignore
- docs/aubuf/generate_plots.sh
- src/aubuf/ajb.c
- src/aubuf/aubuf.c
- In ajb.c change the timestamp unit from RTP timestamps (sample count) to [us]
per sample.
- In aubuf.c adjust the timestamp for an audio frame only if there is partial
read.
> ajb,aubuf: timestamp is given in [us]

- docs/aubuf/.gitignore
- docs/aubuf/generate_plots_multicast.sh
- docs/aubuf/mcconfig/accounts
- docs/aubuf/mcconfig/config
- docs/aubuf/stream_fm4.sh
- src/aubuf/aubuf.c
For multicast listeners there had been overruns at startup of a stream because of late start of player thread. In order to make aubuf independent from start time relation between write and read threads a started flag was added.
- aubuf: add a started flag
- docs: add aubuf plots for multicast
Relates to https://github.com/baresip/retest/pull/64
> aubuf overruns on startup

- src/aubuf/aubuf.c
Zero max_sz means that there is no overrun check wanted. This is used in
baresip audio source modules like `aufile` and `gst` to read the whole file
into an aubuf before pushing to an audio player. Thus this commit fixes these
ausrc modules.
> aubuf: do not drop frames if max size was not set

- src/aubuf/ajb.c
Check ajb before locking and use stored jitter value for printf.
> aubuf/ajb: fix possible null pointer deref

- src/aubuf/aubuf.c
- aubuf: reset ajb on underrun
- aubuf: fade in after underrun
> Fade in on underrun and reset ajb

- include/rem_aubuf.h
- src/aubuf/ajb.c
- src/aubuf/ajb.h
- src/aubuf/aubuf.c
Some functions do not change the struct auframe.
> audio: add optional decoding buffer

- docs/aubuf/ajb.plot
- docs/aubuf/config
- docs/aubuf/generate_plots.sh
- src/aubuf/ajb.c
- src/aubuf/ajb.h
- src/aubuf/aubuf.c
By default the ptime for writing frames to the aubuf is 20ms. If e.g. module
pulse_async is used the ptime for reading dynamically changes and lies around
5ms.
- Compute ptime for get/put separately, and consider channel number.
- Computed jitter was too low. Reset ts0 and tr0 only if a frame is missing.
- Support wish size values that are not a multiple of written frames, if read
frames are smaller. This avoids underruns at the beginning of a stream.
E.g.: 20ms frames are written, 5 ms are read and minimum size is set to 30ms.
Then two calls to `aubuf_get()` after there are 20ms in the aubuf still return
silence frames. The thirds `aubuf_get()` returns the first 5ms frame.
- Remove the +1 byte for max_sz. This makes no sense and no difference.
Tested with:
- pulse and pulse_async
- opus, …
> aubuf: better support for different put/get ptime

- src/aubuf/ajb.c
- src/aubuf/ajb.h
- src/aubuf/aubuf.c
If `audio_buffer_type` is set to `adaptive` and the network does not jitter
noticeably but there might be very sporadic late audio frames then the wish
size can be increased by the user. What this commit does is to keep the average
buffer size between boundaries that respect the given wish size.
> aubuf: the ajb mode should respect wish size

- src/aubuf/ajb.c
- src/aubuf/aubuf.c
The write functions should simply write data to aubuf. The overrun check should
be used only to bound the buffer to the given max size.
On the first read the latency can be controlled by dropping old data.
This simplifies the usage of aubuf by moving the "low latency" buffer drops at start of the stream from write function to the read function.
- aubuf: move low latency start to read function
- aubuf: allow zero as min_sz/wish_sz
> make aubuf usage simpler

- include/rem_auframe.h
- src/auframe/auframe.c
The correct type for timestamp is `uint64_t`.
> auframe: auframe_bytes_to_timestamp use uint64_t

- src/vid/frame.c
Found by CodeQL: Multiplication result may overflow 'unsigned int' before it is converted to 'size_t'.
> vid/frame: fix possbile overflow multiplication

- src/aubuf/aubuf.c
Frame `f` in line 256 may be different from `f` in line 245.
Thus `sz` may be not the correct size in line 257. (E.g. with opus codec where frames have dynamical size)
Then it happend that `ab->cur_sz` underflow, so become a very big unsigned int value.
> aubuf: avoid underflow of cur_sz

- include/rem_auframe.h
- src/auframe/auframe.c
This is useful for packing multiple independent frames into one aubuf and then split them in a separate thread to record multiple tracks.
> auframe: add struct auframe id field

- include/rem_aubuf.h
- src/aubuf/aubuf.c
Dropping old frames on first read is not practicable for the file play
use-case.
> aubuf: add AUBUF_FILE mode

- src/aubuf/ajb.c
Relates to adaptive jitter buffer mode.
Fixes jitter computation and as a consequence a lot of unexpected frame drops if the received RTP stream has an inaccurate timebase.
E.g. the following gstreamer pipeline generates an RTP stream with to fast time base
```
gst-launch-1.0 -v souphttpsrc location=https://orf-live.ors-shoutcast.at/fm4-q1a ssl-strict=false ! decodebin expose-all-streams=false ! audiorate skip-to-first=true ! audioconvert ! audioresample ! avenc_g722 ! rtpg722pay ! udpsink host=224.0.1.194 port=5004
```
The time difference between real time and RTP time stamps becomes more and more negative.
It is 15 us/s too fast.
Here an image of the faulty jitter computation:
> aubuf/ajb: reset reference timestamp if skew is too high

- src/aac/aac.c
- src/auresamp/resamp.c
- src/fir/fir.c
change usage from `ARRAY_SIZE` to `RE_ARRAY_SIZE `
> use RE_ARRAY_SIZE
